// Code generated by "stringer -type OutFormat -linecomment"; DO NOT EDIT.

package outformat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JSON-0]
	_ = x[YAML-1]
	_ = x[TOML-2]
	_ = x[Text-3]
}

const _OutFormat_name = "jsonyamltomltext"

var _OutFormat_index = [...]uint8{0, 4, 8, 12, 16}

func (i OutFormat) String() string {
	if i >= OutFormat(len(_OutFormat_index)-1) {
		return "OutFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutFormat_name[_OutFormat_index[i]:_OutFormat_index[i+1]]
}
