name: Release

on:
  push:
    tags:
      - "v[01].[0-9]+.[0-9]+"

jobs:
  release:
    uses: jalavosus/workflows/.github/workflows/go-release-goreleaser.yml@v1.3.0
    with:
      go_version:         "1.18.x"
      goreleaser_version: "latest"
    secrets:
      token:          ${{ secrets.TAG_PAT }}
      gpg_secret_key: ${{ secrets.GPG_SECRET_KEY }}
      gpg_password:   ${{ secrets.GPG_PASSWORD }}