name: Release

on:
  push:
    tags:
      - "v[01].[0-9]+.[0-9]+"

jobs:
  release:
    uses: jalavosus/workflows/.github/workflows/go-release-goreleaser.yml@v1.5.1
    with:
      go-version:         "1.18.x"
      goreleaser-version: "latest"
    secrets:
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      gpg-password:   ${{ secrets.GPG_PASSWORD }}